---
# Disable SELinux (Amazon Linux / RHEL-like)
- name: Disable SELinux
  command: setenforce 0
  ignore_errors: yes

- name: Ensure SELinux disabled permanently
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  when: ansible_facts['os_family'] == "RedHat"
  ignore_errors: yes

# Disable firewalld (Amazon Linux / RHEL-like)
- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == "RedHat"
  ignore_errors: yes

# Disable ufw (Ubuntu)
- name: Stop and disable ufw
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == "Debian"
  ignore_errors: yes

